apiVersion: v1
kind: Service
metadata:
  name: wp-service
  namespace: wordpress-ns
spec:
  selector:
    app: wordpress
  type : ClusterIP
  ports:
    - port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wordpress-ns
  name: wp-deploy
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: wordpress
        versionNumber: v1
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: "db-service"
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: WORDPRESS_DB_USER
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: WORDPRESS_DB_PASSWORD
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: wordpress
              key: WORDPRESS_DB_NAME

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myappingress
  namespace: wordpress-ns
spec:
  rules:
  - host: whoami.kube
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: wp-service
            port:
              number: 80
